-- ============================================
-- RESET (drop tables) - seguro mesmo se não existirem
-- ============================================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE progress CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE challenges CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE plans CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;
/

-- ============================================
-- TABELA PLANS
-- ============================================
CREATE TABLE plans (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(20) UNIQUE NOT NULL,
  has_ai_chat CHAR(1) DEFAULT 'N',
  has_specialist_chat CHAR(1) DEFAULT 'N'
);

-- insere planos
INSERT INTO plans (name, has_ai_chat, has_specialist_chat) VALUES ('bronze', 'N', 'N');
INSERT INTO plans (name, has_ai_chat, has_specialist_chat) VALUES ('prata',  'Y', 'N');
INSERT INTO plans (name, has_ai_chat, has_specialist_chat) VALUES ('ouro',   'Y', 'Y');

-- ============================================
-- TABELA USERS
-- ============================================
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  email VARCHAR2(100) UNIQUE NOT NULL,
  cpf VARCHAR2(20) UNIQUE NOT NULL,
  password_hash VARCHAR2(200) NOT NULL,
  plan_id NUMBER DEFAULT 1,
  role VARCHAR2(20) DEFAULT 'user',
  selected_challenge_id NUMBER NULL,
  CONSTRAINT fk_user_plan FOREIGN KEY (plan_id) REFERENCES plans(id)
);

-- ============================================
-- TABELA CHALLENGES
-- ============================================
CREATE TABLE challenges (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  description VARCHAR2(1000)
);

-- ============================================
-- TABELA PROGRESS
-- ============================================
CREATE TABLE progress (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER REFERENCES users(id),
  challenge_id NUMBER REFERENCES challenges(id),
  score NUMBER,
  last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- INSERÇÕES INICIAIS
-- ============================================
INSERT INTO challenges (title, description) VALUES 
('Quiz de Soft Skills', 'Responda perguntas sobre comunicação e empatia.');
INSERT INTO challenges (title, description) VALUES 
('Jogo da Adivinhação', 'Tente adivinhar o número secreto entre 1 e 10.');
INSERT INTO challenges (title, description) VALUES 
('Desafio de Digitação', 'Digite frases corretamente o mais rápido possível.');

-- cria um admin padrão no plano 'ouro' (assumindo id 3 para 'ouro')
-- se por algum motivo o ID for diferente, rode uma UPDATE depois.
INSERT INTO users (name, email, cpf, password_hash, plan_id, role)
VALUES ('Administrador', 'admin@skillup.com', '00000000000', 'admin123', 3, 'admin');

COMMIT;
/
