-- ============================================
-- 🔄 RESET DO BANCO DE DADOS (DROP TABLES)
-- ============================================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE progress CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE challenges CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
COMMIT;
/

-- ============================================
-- 🧍 TABELA DE USUÁRIOS
-- ============================================
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    cpf VARCHAR2(20) UNIQUE NOT NULL,
    password_hash VARCHAR2(100) NOT NULL,
    plan VARCHAR2(20) DEFAULT 'bronze',
    role VARCHAR2(20) DEFAULT 'user',
    selected_challenge_id NUMBER NULL
);

-- ============================================
-- 🏆 TABELA DE DESAFIOS
-- ============================================
CREATE TABLE challenges (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    description VARCHAR2(255)
);

-- ============================================
-- 📊 TABELA DE PROGRESSO
-- ============================================
CREATE TABLE progress (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id),
    challenge_id NUMBER REFERENCES challenges(id),
    score NUMBER,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 🌟 INSERÇÃO DE DESAFIOS INICIAIS
-- ============================================
INSERT INTO challenges (title, description) VALUES 
('Quiz de Soft Skills', 'Responda perguntas sobre comunicação e empatia.');
INSERT INTO challenges (title, description) VALUES 
('Jogo da Adivinhação', 'Tente adivinhar o número secreto entre 1 e 10.');
INSERT INTO challenges (title, description) VALUES 
('Desafio de Digitação', 'Digite frases corretamente o mais rápido possível.');

-- ============================================
-- 👨‍💼 ADMIN PADRÃO
-- ============================================
INSERT INTO users (name, email, cpf, password_hash, plan, role)
VALUES ('Administrador', 'admin@skillup.com', '00000000000', 'admin123', 'gold', 'admin');

COMMIT;
/

-- ============================================
-- 🔍 TESTE DE CONSULTA
-- ============================================
SELECT * FROM users;
SELECT * FROM challenges;
SELECT * FROM progress;
